# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('year', models.DateTimeField(verbose_name='year published')),
                ('pages', models.IntegerField(default=0)),
                ('isbn_10', models.IntegerField(default=0)),
                ('isbn_13', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_pics/%Y-%m-%d/', verbose_name='Cover Image')),
                ('add_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
    ]
